---
title: "Analise de pernas de ônibus"
author: "Luiz Alberto Fonseca"
date: "September 5, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(ggplot2)
library(tidyverse)
```


```{r}
dados.bulma <- read_csv("~/Analytics/MBServer/analise/dadostratados.csv")
```

```{r}
# ggplot(dados.bulma, aes(x = as.factor(hourOrig), y = duration)) +
# geom_jitter(aes(alpha = 0.5))
# 
# ggplot(dados.bulma, aes(x = as.factor(hourOrig), y = duration)) +
# geom_boxplot()
```

Agrupando por data e calculando a media e mediana de cada hora.

Calculando a média e mediana para cada hora sem agrupar por data

```{r}
# temp2 <- dados.bulma %>% group_by(hourOrig) %>%
#   summarise(media = mean(duration),
#             mediana = median(duration))
# 
# ggplot(temp2, aes(x = as.factor(hourOrig), y = media, fill = as.factor(hourOrig))) +
#     geom_bar(width = 1, stat="identity")

```

Comparando a hora com as demais horas do dia
(Para aquele dia, como se comporta aquela hora em comparação com as demais)

```{r}
temp1 <- dados.bulma %>% group_by(date, hourOrig) %>%
  summarise(media = mean(duration),
            mediana = median(duration))

# mediana por data
temp3 <- dados.bulma %>%
  group_by(date) %>%
  summarise(median_date = median(duration))

# mediana por data e hora
temp4 <- left_join(temp1, temp3, by = "date")

# Quantos segundos a mediana da hora difere da mediana do dia
temp4 <- temp4 %>% mutate(
  diff_medians = mediana - median_date
)

temp5 <- temp4 %>% group_by(hourOrig) %>%
  summarise(media_diff_mediana = mean(diff_medians))

# plot
ggplot(temp5, aes(as.factor(hourOrig), media_diff_mediana)) +
  geom_bar(stat = "identity", fill = "#2f4c56", legend = FALSE) + 
  scale_y_continuous("Média das diferenças (em segundos)") +
  theme(axis.title.x = element_blank()) +
  labs(title = "Quanto (em média) a mediana das durações de cada hora difere \nda mediana das durações do dia")

```

## Dia da semana
```{r}
summary.weeks <- dados.bulma %>% group_by(weekOfYear) %>%
  summarise(medianWeek = median(duration))

summary.weekdays <- dados.bulma %>% group_by(weekOfYear, weekDay) %>%
  summarise(medianWeekday = median(duration))

summary.weekdays <- left_join(summary.weekdays, summary.weeks, by = "weekOfYear")

summary.weekdays$diffWeekdayToWeek <- summary.weekdays$medianWeekday - summary.weekdays$medianWeek

ggplot(summary.weekdays, aes(as.factor(weekDay), diffWeekdayToWeek)) +
  geom_bar(stat = "identity", fill = "#2f4c56", legend = FALSE) + 
  scale_y_continuous("Média das diferenças (em segundos)") +
  theme(axis.title.x = element_blank()) +
  labs(title = "Quanto (em média) a mediana das durações de cada dia da semana difere \nda mediana das durações da semana")
```

## Área da cidade

```{r}
library(ggmap)

city.area <- dados.bulma %>% select(shapeLatOrig, shapeLonOrig, busStopIdOrig, busStopIdDest, shapeLatDest, shapeLonDest, velocityKmh)
```

